name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.21.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Build Docker image
        run: docker build -t bintabdallah/forgithubaction:latest .

      - name: Push Docker image
        run: docker push bintabdallah/forgithubaction:latest